spring:
  data:
    mongodb:
      database: avantlab
      username: anton
      password: anton

logging:
  file:
    name: 'D:/logs/testProject.log'

  level:
    ru.avantlab: debug
    org.springframework: debug
    org.hibernate: debug
    javax.persistence: debug

  pattern:
    console: "%d{ISO8601} |%-5level | %-16.16thread | %-32.32c | - %msg%n"
    file: "%d{ISO8601} |%-5level | %-16.16thread | %-32.32c | - %msg%n"
