DROP TABLE IF EXISTS persons CASCADE;

create table persons
(
    id         integer generated by default as identity
        constraint person_pkey
            primary key,

    first_name varchar(50),
    last_name  varchar(50),
    email varchar(30) constraint email_key unique,
    phone_number varchar(15) constraint phone_number_key unique
);

INSERT INTO persons (first_name, last_name, email, phone_number) VALUES
('Ivan', 'Ivanov', 'ivan@mail.ru', '1'),
('Petr', 'Petrov', 'petr@mail.ru', '2'),
('Ivan', 'Petrov', 'ivanpetrov@mail.ru', '3');
